#!/usr/bin/env bash
set -Eeuo pipefail
umask 077

die() {
    printf 'ERROR: %s\n' "$*" >&2
    exit 1
}

usage() {
    cat <<'EOF'
Usage: deploy/deploy.sh [install|status|logs|restart|uninstall]

  install     Create/update the project venv and install the systemd service.
  status      Show service status.
  logs        Follow service logs from the journal.
  restart     Restart the service.
  uninstall   Stop and disable the service; preserve .env, venv, and database.
EOF
}

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd -P)"
PROJECT_DIR="$(cd -- "$SCRIPT_DIR/.." && pwd -P)"
VENV_DIR="$PROJECT_DIR/.venv"
ENV_FILE="$PROJECT_DIR/.env"
UNIT_NAME="network-alarm.service"
UNIT_FILE="$PROJECT_DIR/$UNIT_NAME"
ACTION="${1:-install}"

systemd_quote() {
    local value="$1"
    value="${value//\\/\\\\}"
    value="${value//\"/\\\"}"
    value="${value//%/%%}"
    printf '"%s"' "$value"
}

require_user_context() {
    [[ "$EUID" -ne 0 ]] || die "Run this script as the project owner, not via sudo. It invokes sudo only for systemd."
    command -v sudo >/dev/null 2>&1 || die "sudo is required to register the systemd unit."
    sudo -v
}

validate_environment_and_database() {
    cd "$PROJECT_DIR"
    env -i HOME="$HOME" PATH="$PATH" PYTHONPATH="$PROJECT_DIR" \
        "$VENV_DIR/bin/python" - <<'PY'
import sys

from config.settings import (
    ALARM_SOURCE,
    CSV_COLLECTOR_CONFIG,
    DB_CONFIG,
    ORACLE_COLLECTOR_CONFIG,
    PSQL_COLLECTOR_CONFIG,
    TELEGRAM_ADMIN_IDS,
    TELEGRAM_ALERT_CHAT_IDS,
    TELEGRAM_BOT_TOKEN,
)

errors = []
if not TELEGRAM_BOT_TOKEN:
    errors.append("TELEGRAM_BOT_TOKEN is required")
if not TELEGRAM_ALERT_CHAT_IDS:
    errors.append("TELEGRAM_ALERT_CHAT_IDS must include at least one alert chat/group")
elif any(not chat_id.lstrip("-").isdigit() for chat_id in TELEGRAM_ALERT_CHAT_IDS):
    errors.append("TELEGRAM_ALERT_CHAT_IDS must contain numeric Telegram chat IDs")
if not TELEGRAM_ADMIN_IDS:
    errors.append("TELEGRAM_ADMIN_IDS must be set; an empty list allows everyone to use lookup commands")
elif any(not user_id.isdigit() for user_id in TELEGRAM_ADMIN_IDS):
    errors.append("TELEGRAM_ADMIN_IDS must contain numeric Telegram user IDs")
if DB_CONFIG["password"] in ("", "postgres"):
    errors.append("Set a non-default PG_PASSWORD in .env")
if ALARM_SOURCE not in ("csv", "oracle", "psql"):
    errors.append("ALARM_SOURCE must be csv, oracle, or psql")
if ALARM_SOURCE == "oracle":
    for key in ("host", "service_name", "user", "password"):
        if not ORACLE_COLLECTOR_CONFIG[key]:
            errors.append(f"ORACLE_{key.upper()} is required when ALARM_SOURCE=oracle")
if ALARM_SOURCE == "psql":
    for key in ("host", "dbname", "user", "password"):
        if not PSQL_COLLECTOR_CONFIG[key]:
            errors.append(f"PSQL_{key.upper()} is required when ALARM_SOURCE=psql")
if ALARM_SOURCE == "csv":
    from pathlib import Path

    csv_path = Path(CSV_COLLECTOR_CONFIG["file_path"])
    if not csv_path.is_absolute():
        csv_path = Path.cwd() / csv_path
    if not csv_path.is_file():
        errors.append(f"Alarm CSV file does not exist: {csv_path}")

if errors:
    print("Configuration errors:", file=sys.stderr)
    for error in errors:
        print(f"- {error}", file=sys.stderr)
    raise SystemExit(1)

try:
    import psycopg2

    connection = psycopg2.connect(**DB_CONFIG)
    try:
        with connection.cursor() as cursor:
            tables = (
                "node",
                "station",
                "device",
                "topo_link",
                "alarm_event",
                "telegram_outbox",
                "telegram_outbox_control",
                "telegram_chat_limits",
            )
            missing = []
            for table in tables:
                cursor.execute("SELECT to_regclass(%s)", (table,))
                if cursor.fetchone()[0] is None:
                    missing.append(table)
        if missing:
            print(
                "Database schema is incomplete. Missing tables: " + ", ".join(missing),
                file=sys.stderr,
            )
            raise SystemExit(1)
    finally:
        connection.close()
except psycopg2.Error as exc:
    print(f"Cannot connect to PostgreSQL: {exc.__class__.__name__}", file=sys.stderr)
    raise SystemExit(1)

print("Configuration and PostgreSQL schema check passed.")
PY
}

write_unit_file() {
    if [[ -e "$UNIT_FILE" ]]; then
        [[ ! -L "$UNIT_FILE" ]] || die "$UNIT_FILE is a symlink; refusing to overwrite it."
        grep -q 'Generated by deploy/deploy.sh' "$UNIT_FILE" \
            || die "$UNIT_FILE already exists and is not installer-generated; move it aside first."
    fi

    local service_user service_group
    service_user="$(id -un)"
    service_group="$(id -gn)"

    cat > "$UNIT_FILE" <<EOF
# Generated by deploy/deploy.sh. Re-run that script to update this unit.
[Unit]
Description=Network Alarm Bot and Collector
Wants=network-online.target
After=network-online.target
StartLimitIntervalSec=300
StartLimitBurst=5

[Service]
Type=simple
User=$service_user
Group=$service_group
WorkingDirectory=$PROJECT_DIR
ExecStart=$VENV_DIR/bin/python -m alerting.bot.app
Environment=PYTHONUNBUFFERED=1
Environment=PYTHONDONTWRITEBYTECODE=1
Restart=on-failure
RestartSec=10
TimeoutStartSec=60
TimeoutStopSec=40
UMask=0077
NoNewPrivileges=true
PrivateTmp=true
ProtectSystem=full

[Install]
WantedBy=multi-user.target
EOF
    chmod 644 "$UNIT_FILE"
}

install_service() {
    require_user_context
    command -v systemctl >/dev/null 2>&1 || die "systemctl was not found; this host must use systemd."
    command -v "$PYTHON_BIN" >/dev/null 2>&1 || die "Python 3 was not found."

    if ! "$PYTHON_BIN" -c 'import sys; raise SystemExit(0 if sys.version_info >= (3, 10) else 1)'; then
        die "Python 3.10 or newer is required."
    fi

    if [[ ! -f "$ENV_FILE" ]]; then
        cp "$PROJECT_DIR/.env.example" "$ENV_FILE"
        chmod 600 "$ENV_FILE"
        die "Created .env from .env.example. Edit credentials/settings, then run install again."
    fi
    chmod 600 "$ENV_FILE"

    if [[ ! -x "$VENV_DIR/bin/python" ]]; then
        "$PYTHON_BIN" -m venv "$VENV_DIR" \
            || die "Could not create the virtualenv. Install the OS package for Python venv support."
    fi
    "$VENV_DIR/bin/python" -m pip install --upgrade pip
    "$VENV_DIR/bin/python" -m pip install -r "$PROJECT_DIR/requirements.txt"
    validate_environment_and_database
    write_unit_file
    command -v systemd-analyze >/dev/null 2>&1 \
        || die "systemd-analyze was not found; cannot validate the generated unit."
    sudo systemd-analyze verify "$UNIT_FILE"

    sudo systemctl daemon-reload
    sudo systemctl enable "$UNIT_FILE"
    if sudo systemctl is-active --quiet "$UNIT_NAME"; then
        sudo systemctl restart "$UNIT_NAME"
    else
        sudo systemctl start "$UNIT_NAME"
    fi

    printf 'Installed and started %s\n' "$UNIT_NAME"
    printf 'Unit file remains in the project: %s\n' "$UNIT_FILE"
    printf 'Manage it with: %s status|logs|restart|uninstall\n' "$SCRIPT_DIR/deploy.sh"
}

manage_service() {
    require_user_context
    command -v systemctl >/dev/null 2>&1 || die "systemctl was not found; this host must use systemd."

    case "$ACTION" in
        status)
            sudo systemctl status "$UNIT_NAME" --no-pager
            ;;
        logs)
            sudo journalctl -u "$UNIT_NAME" -f
            ;;
        restart)
            sudo systemctl restart "$UNIT_NAME"
            ;;
        uninstall)
            sudo systemctl disable --now "$UNIT_NAME"
            sudo systemctl daemon-reload
            rm -f "$UNIT_FILE"
            printf "Disabled %s. Project files, .env, virtualenv, and database were preserved.\n" "$UNIT_NAME"
            ;;
        *)
            usage
            exit 2
            ;;
    esac
}

PYTHON_BIN="${PYTHON_BIN:-python3}"
case "$ACTION" in
    install)
        install_service
        ;;
    status|logs|restart|uninstall)
        manage_service
        ;;
    -h|--help|help)
        usage
        ;;
    *)
        usage
        exit 2
        ;;
esac